// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/4/2025, 7:11:22 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/workspaces/shopping_cart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/plugins/**/*.{js,ts,mjs}","/workspaces/shopping_cart/composables/**/*.{js,ts,mjs}","/workspaces/shopping_cart/utils/**/*.{js,ts,mjs}","/workspaces/shopping_cart/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/shopping_cart/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;